import '../styles/globals.sass'; // Import global styles
import type { Metadata } from 'next';
import ThemeProviders from './theme-providers';

export const metadata: Metadata = {
    title: 'My Next.js App', // Default title, can be customized per page
    description: 'Generated by Next.js',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    // The `pageProps` that _app.tsx received (like recaptchaKey or initial data for providers)
    // needs a new way to be passed in the App Router.
    // For now, ThemeProviders will use default/empty initial values or fetch data itself.
    // This might require adjustments later depending on how these props were used.
    // For instance, recaptchaKey might be passed differently or initialized in a client component.
    const pageProps = {}; // Placeholder

    return (
        <html lang="en">
            <body>
                <ThemeProviders pageProps={pageProps}>
                    {children}
                </ThemeProviders>
            </body>
        </html>
    );
}
